name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

      # 2. Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: main

    # 3. Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build Maxxy-Tiles
      run: npm run maxxy-tiles:build

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/maxxy-tiles/browser s3://brazukka-websites
