name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: main

    # 2. Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'

