name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCES_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # 2. Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: main

    # 3. Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.13.0'

    # 4. Install Dependencies for the nx-monorepo
    - name: Install dependencies
      run: npm ci

    # 5. Build the Maxxy-Tiles application
    - name: Build Maxxy-Tiles
      run: npm run maxxy-tiles:build

    # 6. Deploy to AWS
    - name: Deploy to AWS
      if: success()
      run: aws s3 sync ./dist/maxxy-tiles/browser s3://brazukka-websites
